id: AA662C390
title: 'Wisdom Nexus: A Guru Sādhana'
type: translation
pechas:
- I438D0DD4
- IF2851BA4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:56:28.446413
  last_modified_at: 2023-01-04 12:56:28.446433
  collections:
  - Lachung Apo Series
  - Works of Tibetan Masters
alignment_to_base:
  I438D0DD4/A8CA: B2B1
  IF2851BA4/B9CB: B2B1
